export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const SET_DEFAULT_VIEW = "SET_DEFAULT_VIEW";
export const SET_DM_VIEW = "SET_DM_VIEW";
export const SET_SERVER_VIEW = "SET_SERVER_VIEW";
export const SET_SEARCH_VIEW = "SET_SEARCH_VIEW";
